### ISSUE TITLE
MrMorningstar - Users can lose their rewards and their funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-07-sense-points-marketplace-judging#141]
MrMorningstar

High

# Users can lose their rewards and their funds

## Summary
Users will lose their rewards even if they payed fee on claim.
When user claim their point reward tokens and pay the fee when claiming they should be able to redeem rewards (without fees for the amount they claimed).
## Vulnerability Detail
PoC:
Imagine scenario user 1 (Tolly) claim his token and pay fee on that token so naturally he should be able to redeem rewards for that. But instead of redeeming he first send claimed tokens to user 2 (Vitalik) and then our user 1 try to redeem his rewards on claimed tokens that he payed fees. But he could not he would lost that rewards even if he payed fee for claiming and all rewards would go to user to for redeeming.
To prove this add following code to [PointTokenVault.t.sol](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-mrMorningstar96/blame/main/point-tokenization-vault/contracts/test/PointTokenVault.t.sol#L21):

- First add mint fee and modify [test_DistributionTwoRecipients](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-mrMorningstar96/blame/5259bb49de2294ca1593b0a403b1d8afb1c9b2dc/point-tokenization-vault/contracts/test/PointTokenVault.t.sol#L287):
```diff
    function test_DistributionTwoRecipients() public {
        // Merkle tree created from leaves [keccack(vitalik, pointsId, 1e18), keccack(toly, pointsId, 0.5e18)].
        bytes32 root = 0x4e40a10ce33f33a4786960a8bb843fe0e170b651acd83da27abc97176c4bed3c;

        vm.prank(merkleUpdater);
        pointTokenVault.updateRoot(root);

        // Set mint fee to 10%
+        vm.prank(operator);
+        pointTokenVault.setMintFee(0.1e18); // 10% in WAD

        bytes32[] memory vitalikProof = new bytes32[](1);
        vitalikProof[0] = 0x6d0fcb8de12b1f57f81e49fa18b641487b932cdba4f064409fde3b05d3824ca2;

        // Vitalik can claim
        vm.prank(vitalik);
        pointTokenVault.claimPTokens(PointTokenVault.Claim(eigenPointsId, 1e18, 1e18, vitalikProof), vitalik, vitalik);

-        assertEq(pointTokenVault.pTokens(eigenPointsId).balanceOf(vitalik), 1e18);
+        assertEq(pointTokenVault.pTokens(eigenPointsId).balanceOf(vitalik), 0.9e18);

        bytes32[] memory tolyProof = new bytes32[](1);
        tolyProof[0] = 0x77ec2184ee10de8d8164b15f7f9e734a985dbe8a49e28feb2793ab17c9ed215c;

        // Illia can execute toly's claim, but can only send the tokens to toly
        vm.prank(illia);
        vm.expectRevert(PointTokenVault.ProofInvalidOrExpired.selector);
        pointTokenVault.claimPTokens(PointTokenVault.Claim(eigenPointsId, 0.5e18, 0.5e18, tolyProof), illia, illia);

        pointTokenVault.claimPTokens(PointTokenVault.Claim(eigenPointsId, 0.5e18, 0.5e18, tolyProof), toly, toly);
-        assertEq(pointTokenVault.pTokens(eigenPointsId).balanceOf(toly), 0.5e18);
+        assertEq(pointTokenVault.pTokens(eigenPointsId).balanceOf(toly), 0.45e18);
        
    }
```
- Then copy following test below :
```js
  function test_sendPTokensAndLoseRewards() public {
        test_DistributionTwoRecipients();

        // Toly transfer claimed tokens to Vitalik
        vm.startPrank(toly);
        console.log('Toly Balance Before Transfer:', pointTokenVault.pTokens(eigenPointsId).balanceOf(toly));
        console.log('Vitalik Balance Before Transfer:', pointTokenVault.pTokens(eigenPointsId).balanceOf(vitalik));
        pointTokenVault.pTokens(eigenPointsId).transfer(vitalik, 0.45e18);
        console.log('Vitalik Balance After Transfer:', pointTokenVault.pTokens(eigenPointsId).balanceOf(vitalik));
        console.log('Toly Balance After Transfer:', pointTokenVault.pTokens(eigenPointsId).balanceOf(toly));


        rewardToken.mint(address(pointTokenVault), 3e18);
        vm.stopPrank();


        vm.startPrank(operator);
        pointTokenVault.setRedemption(eigenPointsId, rewardToken, 1e18, false);

        // Set redemption fee to 5%
        pointTokenVault.setRedemptionFee(0.05e18); // 5% in WAD
        vm.stopPrank();


        bytes32[] memory none = new bytes32[](0);

        // Toly try to redeem rewards on tokens he claimed and payed fees
        vm.startPrank(toly);
        console.log('Toly Balance PT Before Redeem:', pointTokenVault.pTokens(eigenPointsId).balanceOf(toly));

        // It will revert and Toly would lost all his rewards
        vm.expectRevert();
        pointTokenVault.redeemRewards(PointTokenVault.Claim(eigenPointsId, 0.45e18, 0.45e18, none), toly);
        console.log('Reward balance Toly after redeem:', rewardToken.balanceOf(toly));
        vm.stopPrank();

        // Redeem rewards
        bytes32[] memory empty = new bytes32[](0);

        // Vitalik try to claim rewards on all tokens he have (His + Tolly's amount)
        vm.startPrank(vitalik);
        console.log('Vitalik Balance PT Before Redeem:', pointTokenVault.pTokens(eigenPointsId).balanceOf(vitalik));
        pointTokenVault.redeemRewards(PointTokenVault.Claim(eigenPointsId, 1.35e18, 1.35e18, empty), vitalik);
        console.log('Reward balance Vitalik after redeem:', rewardToken.balanceOf(vitalik));
        vm.stopPrank();
    }
```
These are the results:
```terminal
  Toly Balance Before Transfer: 450000000000000000
  Vitalik Balance Before Transfer: 900000000000000000
  Vitalik Balance After Transfer: 1350000000000000000
  Toly Balance After Transfer: 0
  Toly Balance PT Before Redeem: 0
  Reward balance Toly after redeem: 0
  Vitalik Balance PT Before Redeem: 1350000000000000000
  Reward balance Vitalik after redeem: 1332500000000000000
```
This shows us that user 1 (Tolly) will lose their rewards even if he payed the fee on claim if he send his token to someone else and also his funds(fee he payed on claim and the amount he transffered).
## Impact
Users can lose their rewards and their funds
## Code Snippet
https://github.com/sherlock-audit/2024-07-sense-points-marketplace-mrMorningstar96/blame/5259bb49de2294ca1593b0a403b1d8afb1c9b2dc/point-tokenization-vault/contracts/PointTokenVault.sol#L172
## Tool used

Manual Review

## Recommendation
Make sure users can always redeem rewards on the tokens they claimed and payed fees.

**Comment by mrMorningstar96** [comment]
Escalation
Based on conversation and confirmation with sponsor the rewards should remain with user number 1, not user 2 which this issue prove that user 1 will lose all his rewards
![escalation](https://github.com/user-attachments/assets/03d16e55-d353-4c5c-8d2d-a51a841a5cf4)

**Comment by blockchain555** [comment]
Escalate
Based on conversation and confirmation with sponsor the rewards should remain with user number 1, not user 2 which this issue prove that user 1 will lose all his rewards
![image](https://github.com/user-attachments/assets/461df7da-1813-4feb-88af-645dfd56c058)

**Comment by sherlock-admin3** [comment]
> Escalate
> Based on conversation and confirmation with sponsor the rewards should remain with user number 1, not user 2 which this issue prove that user 1 will lose all his rewards
> ![image](https://github.com/user-attachments/assets/461df7da-1813-4feb-88af-645dfd56c058)
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mrMorningstar96** [comment]
I believe this is the real issue and the PoC proved that user 1 in this case will lose all rewards even when he payed fee for claim. The sponsors clearly stated that user 1 even in the mentioned case should be able to redeem his rewards as you can see in the screenshot provided in the escalation.

**Comment by WangSecurity** [comment]
Can the user 1 get back their token and get the rewards? and could you also link me the exact line where the redemption reverts?

**Comment by mrMorningstar96** [comment]
No sir, because tokens are already transferred to user 2 and now they belong to him and the rewards that go with that tokens too, which breaks one of the core principle of the protocol
` users should be able to redeem rewards (fee less too) for the token amount that they claimed and payed fee`. 

If we delete or comment out `vm.expectRevert();` from my test it will revert when redeemReward function tries to burn 
Link for the line is [here](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-mrMorningstar96/blame/5259bb49de2294ca1593b0a403b1d8afb1c9b2dc/point-tokenization-vault/contracts/PointTokenVault.sol#L192)
```js
pTokens[pointsId].burn(msg.sender, pTokensToBurn);
```
Which indicate that it tries to burn amount that user don't have, which confirm that user lost his rewards even thou he claimed and payed fees for tokens. Which also confirms  that one of the core principle of the protocol is broken
` users should be able to redeem rewards (fee less too) for the token amount that they claimed and payed fee`.

**Comment by jsmi0703** [comment]
1. At first, discord conversation can't be source of trueth.
2. If user1 sold pTokens to user2, he can't redeem for that pTokens, this is design choice. It's because user1 received other tokens which price is equal  to that sold pTokens. It doesn't make sense for user1 to redeem pTokens he have already sold.

**Comment by mrMorningstar96** [comment]
1. These are not some random people, these are actual sponsors of the contest and any doubt we as auditors have we should ask for them to clarify if for us if we cannot find answer in the documentation or code itself, so their answer should be accounted
2. The design choice (one of them) is that users should always be able to redeem rewards for the amount of tokens they claimed and payed fee to the protocol , which we can get confirmation from their reply also that I provided above, which this issue proved it does not hold always as it should be. This is one of  the reasons why also claiming tokens and redeeming rewards as separate functions makes more sense instead making them as one. This further proof their design choice and the conversation I provided above.

**Comment by WangSecurity** [comment]
But, user 1 (or Tolly) still can get the rewards without paying the fee, but they still have to have the pTokens to redeem rewards. Moreover, the user can buy the pTokens, redeem the rewards and sell pTokens back (even in the same transaction) without suffering a loss. 

Hence, I believe that this report is not Medium severity, while can also be a viable design decision that the users without pTokens cannot redeem the rewards.

Planning to reject the escalation and leave the issue as it is.

**Comment by mrMorningstar96** [comment]
The user 1 can buy tokens and redeem rewards that is true, but that would require even more funds to be spend by the user (fee that he payed to the protocol when claimed tokens + additional funds to buy tokens again)
The sponsors stated clearly that in that case user 1 should be able to redeem his rewards that he already claimed, which also goes with intended design of the protocol that users should be able to redeem rewards for the amount they claimed and payed fee already. Which this case prove that user 1 will lose rewards and also pTokens. Many users can be mislead by thinking that when they claim rewards and pay fees to the protocol can redeem rewards, but if they transfer they tokens they will lose the rewards and then they need to spend additional money to rebuy pTokens again if they want to redeem rewards.
@WangSecurity

**Comment by WangSecurity** [comment]
Thank you for re-iterating on this again, but, still, these funds, i.e. rewards, can be received if the users gets Ptokens and the can buy them, get the rewards, sell tokens at the same transaction without any loss of value. Hence, I believe this issue is still low-severity. Planning to reject the escalation and leave the issue as it is.

**Comment by mrMorningstar96** [comment]
No user cannot sell pTokens after receiving rewards and that cannot happen in same transaction
If user sell the pTokens or just transfer it without selling for whatever reason he would not be able to redeem rewards even if he payed fee when he claimed tokens
He can buy more tokes from other users but that will require for him to spend even more money to buy pTokens so he can redeem rewards and in the end he will be at loss because he must pay extra to get new tokens plus the fee amount he already payed when claimed tokens in the first place
Also the sponsors clearly stated that in the case that is presented here user 1 should be able to redeem rewards even when the tokens are transferred to user 2, which again goes with protocol core principle and design and that is: "users should be able to redeem rewards for the amount of pTokens they claimed and payed fee to the protocol"

Which this issue prove is not in this case, and that could mislead users into losing rewards and tokens and trust of the protocol and dissatisfaction of the protocol users

Since this all goes against protocol principles and intentions that sponsors confirmed also + the loss of rewards and funds for users, I think it should be valid issue
@WangSecurity

**Comment by WangSecurity** [comment]
> He can buy more tokes from other users but that will require for him to spend even more money to buy pTokens so he can redeem rewards and in the end he will be at loss because he must pay extra to get new tokens plus the fee amount he already payed when claimed tokens in the first place

To clarify this part, they indeed have to pay the fee second time, even though they paid it before?

Also, but buying pTokens doesn't involve the loss, because they should've been get something in exchange. For example, 1 pToken == 1 USDC (arbitrary example), the user paid the fee and can get the rewards, but they've sold their tokens to another user. For example, the fee is 1 pToken and they've sold the remaining 9 pTokens for 9 USDC, then they can again buy those pTokens for 9 USDC, get the rewards and sell those pTokens again. What is incorrect in this example?

**Comment by mrMorningstar96** [comment]
No you misread that part I talk about the fee he already payed when he made the first claim + the extra amount to rebuy the pTokens again, they need to pay fee if they redeem more than they claimed.
There is no guarantee in your example that user can buy again pTokens for the same amount he sold them, maybe he would need to pay more second time to get the same amount so he would encounter a loss there (maybe he would need to pay 10 USDC for the 9 pTokens).
Also there could be scenario where maybe he could not buy them again at all (maybe some small limited amount of tokens), so in that scenario he will be at loss also because he payed fee when he claimed them and he would lose the rewards and also pTokens because he would not be able to buy them anymore even if he want. (that is the worst case scenario)
@WangSecurity

**Comment by jsmi0703** [comment]
@mrMorningstar96 
1. Your escalation is based on Discord Message which can't be source of truth by the following Sherlock judging rule:
> Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README.

2. In the scenario of this report, user should know that if he sold PTs, he couldn't redeem without fee for those PTs. It is the user's responsibility not to sell PTs for redeeming without fee. In addition, since user's misbehavior only damage user himself, it can't have medium severity.

**Comment by mrMorningstar96** [comment]
1. The escalation is not based on discord message, it is based on protocol intended design and behavior, the messages I provided are here just as a proof and confirmation about that. There is no conflict with contest README, but quite opposite just further confirmation about intended design and behavior of the protocol. Your provided text should not be applied here.

2. This issue is not about fees, its about losing rewards and funds even when fees are payed to the protocol. I suspect on lack of understanding of this issue here by the answer.

Since this issue proved that intended design and behavior of the protocol (which sponsors also confirmed) will be broken + users will lose rewards and funds (which could impact many users) I still believe this issue should be valid.

**Comment by WangSecurity** [comment]
I've confirmed this scenario additionally with the team and their message in the screenshot wasn't precise. In this scenario, User 1 (as in the screenshot) or Tolly (as in the report) still has to obtain the pTokens to receive rewards, even though they've paid all the fees, but sent the tokens to another user.

Therefore, the issue is the intended design and the protocol works as expected. Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [blockchain555](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/141/#issuecomment-2326177180): rejected
