### ISSUE TITLE
0x73696d616f - Malicious user will call `PointTokenVault::collectFees()` after a redemption was disabled to lose all `rewardTokenFeeAcc`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-07-sense-points-marketplace-judging#185]
0x73696d616f

Medium

# Malicious user will call `PointTokenVault::collectFees()` after a redemption was disabled to lose all `rewardTokenFeeAcc`

### Summary

The `solmate` `SafeTransferLib::safeTransfer()` does [not](https://github.com/transmissions11/solmate/blob/main/src/utils/SafeTransferLib.sol#L85) check if the token has code, which will not revert for an `address(0)` token. Thus, if redemptions are [disabled](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L312) (setting `redemptions[pointsId].rewardToken` is how redemptions are enabled), but there were fees in `rewardTokenFeeAcc[_pointsId]`, an attacker may call `PointTokenVault::collectFees()` to clear the fees mapping without transferring any tokens to the `feeCollector`.

### Root Cause

In [PointTokenVault:353](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L353), it does not check if the `rewardToken` is not null, allowing anyone to clear the mapping of the fees without the `feeCollector` ever receiving the tokens.

### Internal pre-conditions

1. Admins needs to disable redemptions (set `redemptions[pointsId].rewardToken` to `address(0)`) after fees have been accrued in `rewardTokenFeeAcc[_pointsId]`

### External pre-conditions

None.

### Attack Path

1. Users call `PointTokenVault::redeemRewards()` and add fees to `rewardTokenFeeAcc[pointsId]`.
2. Admin disables redemptions by setting `redemptions[pointsId].rewardToken` to `address(0)`, but there were fees in `rewardTokenFeeAcc[pointsId]` pending (could have been frontrun).
3. Attackers call `PointTokenVault::collectFees()` and clear the fees without sending tokens to the `feeCollector`.

### Impact

The protocol loses all fees.

### PoC

```solidity
function safeTransfer(address token, address to, uint256 amount) internal {
    /// @solidity memory-safe-assembly
    assembly {
        mstore(0x14, to) // Store the `to` argument.
        mstore(0x34, amount) // Store the `amount` argument.
        mstore(0x00, 0xa9059cbb000000000000000000000000) // `transfer(address,uint256)`.
        // Perform the transfer, reverting upon failure.
        if iszero(
            and( // The arguments of `and` are evaluated from right to left.
                or(eq(mload(0x00), 1), iszero(returndatasize())), // Returned 1 or nothing.
                call(gas(), token, 0, 0x10, 0x44, 0x00, 0x20) //@audit returns 1 if token == address(0)
            )
        ) {
            mstore(0x00, 0x90b8ec18) // `TransferFailed()`.
            revert(0x1c, 0x04)
        }
        mstore(0x34, 0) // Restore the part of the free memory pointer that was overwritten.
    }
}
```

### Mitigation

Explicitely check if the `rewardToken` is not null in `PointTokenVault::collectFees()` before claiming the fees.

**Comment by jparklev** [comment]
PR fix: https://github.com/sense-finance/point-tokenization-vault/pull/36

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sense-finance/point-tokenization-vault/pull/36

**Comment by 0xHuntoor** [comment]
Escalate

The core of this report is the fact that owner will disable redemption of a token with fees pending

this should be invalid under this Sherlock rule
> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.

now the report says that:
> Admin disables redemptions by setting redemptions[pointsId].rewardToken to address(0), but there were fees in rewardTokenFeeAcc[pointsId] pending (could have been frontrun).
> > pending (could have been frontrun).

Admin can `collectFees` first then call the mentioned disable method in the same txn hence the sherlock rule applies

In addition to that, Admin can 
1. disable redemption by setting `rewardsPerPToken` to 0 first so that any users call to `redeemRewards` reverts
2. call `collectFees`
3. calls `setRedemption` again to set  `rewardsPerPToken` and `rewardToken` to address zero

in that way no space for users to call `redeemRewards` between admin calls

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The core of this report is the fact that owner will disable redemption of a token with fees pending
> 
> this should be invalid under this Sherlock rule
> > Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.
> 
> now the report says that:
> > Admin disables redemptions by setting redemptions[pointsId].rewardToken to address(0), but there were fees in rewardTokenFeeAcc[pointsId] pending (could have been frontrun).
> > > pending (could have been frontrun).
> 
> Admin can `collectFees` first then call the mentioned disable method in the same txn hence the sherlock rule applies
> 
> In addition to that, Admin can 
> 1. disable redemption by setting `rewardsPerPToken` to 0 first so that any users call to `redeemRewards` reverts
> 2. call `collectFees`
> 3. calls `setRedemption` again to set  `rewardsPerPToken` and `rewardToken` to address zero
> 
> in that way no space for users to call `redeemRewards` between admin calls

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xsimao** [comment]
There is no mention of how often or under which cicumstances the admin will call the function, so we can not assume how the admin will act. In fact, the admin may rely on someone else to collect the fees and sponsor the gas, not bothering with collecting fees. 

As such, the admin may intend to keep the fees in the contract before disabling the reward token. For example, in case the reward token is disabled for a short amount of time and then enabled again, the admin could opt to not collect the fees before disabling and rely on someone else to collect them after enabling again.

Given these 2 paragraphs, the rule is not applicable to this scenario as there was no description of how these 2 functions would be called and there are proper ways for them to be called that lead to loss of funds.

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.

**Comment by WangSecurity** [comment]
Arguments on both side are fair, but still there is a proper way for the admin to collect the fees without a loss and then disable the redemptions. Hence, I believe the escalation was correct and we have to assume that the admins would do everything to not lose funds, which is the case here. 

Moreover, I believe the following rule applies:
> Admin could have an incorrect call order. Example: If an Admin forgets to setWithdrawAddress() before calling withdrawAll() This is not a valid issue

The admin can collect the fees and then disable the redemptions, which can be viewed as the correct call order without any loss of funds.

Planning to accept the escalation and invalidate the issue.

**Comment by 0xsimao** [comment]
@WangSecurity the `collectFees()` function is permissionless, it is not an incorrect action to disable the reward token and leaving rewards pending. If you take a look at the [fix](https://github.com/sense-finance/point-tokenization-vault/pull/36/files#diff-52816072384285e2860d58a66e9aa2714285d0f04c1450ebc731110550b94566R356-R358), the `collectFees()` call does nothing if the reward token has not been set, which means the sponsor expects that fees may be pending collection while the reward token is disabled.

For example, if the protocol intends to collect fees every 100 USD, but at the time of disabling rewards the fees were 90 USD, it would not make sense for them to collect the fees. This is also a correct call order.

**Comment by WangSecurity** [comment]
@0xsimao thank you for elaborating on your point again. Excuse me, for the confusion, I didn't mean to say that the process you suggest is incorrect. I meant to say that even though it may be a viable process, still, the admins can claim all their fees in a way they don't lose anything. Hence, we should assume will follow this path and not the one that would cause a loss of fees. Hope that clears your concern, if not, please ask more questions.

Planning to accept the escalation and invalidate this issue.

**Comment by 0xsimao** [comment]
@WangSecurity could you clarify why we should assume they will go for the path that does not lead to loss of funds? there is no evidence of such in the readme, documentation or code. Without knowing this issue, both paths are valid and do not lead to loss of funds.

Given Sherlock's rules, the fact that there is 1 path that does not lead to loss of funds is a constraint, which may decrease the severity of the issue, but not invalidate it.

**Comment by WangSecurity** [comment]
Firstly, this as quoted in the escalation comment:
> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.

Secondly, this:
> Admin could have an incorrect call order. Example: If an Admin forgets to setWithdrawAddress() before calling withdrawAll() This is not a valid issue

Which also applicable here since the call order to first collect the fees and then disable the redemption doesn't lead to a loss of funds. That's why I say it's "correct" because it doesn't lead to a loss of funds, while an order you suggest leads to a loss of funds.

Moreover, we should always assume the admin will do everything they can to not cause or suffer loss of funds. Hence, the decision remains, accept the escalation and invalidate the report.

**Comment by 0xsimao** [comment]
@WangSecurity if the gas fees are bigger or around the same value as the fee, why would the admin collect them? The proper action by the admin would be to ignore it, or he would take a loss. Or even if the fee is bigger than the gas cost, if there is a gas spike and the admin would have to spend a significant amount of gas, the correct action would be to wait for times where gas is cheaper.  

For example, If there is a 90 USD fee to collect, but gas fees are 9 USD, it is not economically advisable for the admin to collect them. If the admin does this every time, the profit would be reduced by 10%. The right thing is waiting for the fee to grow to a value where the gas cost is negligible.

When gas costs are bigger than the fee, loss of funds would be calling `collectFees()` before disabling rewards and the admin will do everything he can to avoid it. Or, if gas costs are considerable when compared to the fees, such as 10%, the admin will still avoid taking this loss and will wait for fees to accumulate and/or gas prices to decrease.


The first rule is not applicable since when gas fees are high, it will always lead to loss of funds (it is never profitable for the admin). The second rule is not applicable because the order mentioned in this issue is correct (economically speaking, without being aware of this bug).

**Comment by 0xHuntoor** [comment]
@WangSecurity @0xsimao 
Never wanted to repeat my arguments, but i feel that Both of you sirs excluding this part of my escalation

![image](https://github.com/user-attachments/assets/f77666d9-eddb-433a-9269-d48efae5ee68)

So when Admin disables Redemptions by the above described way, then the issue won't arise and there can be pending fees.

But instead, Watson chose the worst case scenario of disabling redemption
- Which is viable argument but not with an admin action

**Comment by 0xsimao** [comment]
@IlIlHunterlIlI how does that change the fact that it may not make sense for the admin to go though these steps? For instance if they rely on someone else to collect fees and sponsor the gas? or the gas spikes and the gas cost is similar to the fee (above 10% of the fee) to collect and the admin should collect it in a future time when gas costs are lower and/or there is more fee to collect? The `collectFees()` function is not even admin permissioned, which reinforces this course of actions.

**Comment by 0xHuntoor** [comment]
@0xsimao 
Replying on every part
> @IlIlHunterlIlI how does that change the fact that it may not make sense for the admin to go though these steps? 

yes it may not make sense, but this is how admin rule works

> For instance if they rely on someone else to collect fees and sponsor the gas? or the gas spikes and the gas cost is similar to the fee (above 10% of the fee) to collect and the admin should collect it in a future time when gas costs are lower and/or there is more fee to collect? The `collectFees()` function is not even admin permissioned, which reinforces this course of actions.

As i have said above admin can set `rewardsPerPToken` to 0 and call `claimFees` any time he wants after, doesn't have to be in same txn
- when `rewardsPerPToken` is 0, any call to `redeemRewards` will revert due to division by 0
- then he can collect or postpone the fee collection

**Comment by 0xsimao** [comment]
> yes it may not make sense, but this is how admin rule works

> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.

When the fee is relatively small and gas costs are high the proper use is not collecting the fee.

**Comment by jsmi0703** [comment]
> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.

This means that admin will collect fees before disable redemption as long as the total fee amount is larger than gas costs.

**Comment by 0xHuntoor** [comment]
@0xsimao what do you think about the second half of my comment?

The way i described the correct flow of disabling a redemption.

**Comment by 0xsimao** [comment]
@IlIlHunterlIlI they could use it as a workaround fix but it is not even intended given the fact that it relies on a division by `0` to work. And also some situations such as the one mentioned previously are not economically advisable to do it anyway. This means that it is not always the correct flow and there is no evidence the admins would do it.

**Comment by jsmi0703** [comment]
Of course, when gas spikes, admin will not collect fees in general cases.
But admin will collect fees just before disabling redemption even though gas costs is over 10% of fees in order to not losing total fees due to the following Sherlock rule.
> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned function can be used properly.

**Comment by 0xsimao** [comment]
@jsmi0703 a 10% cost in fees is not a proper use.

**Comment by jsmi0703** [comment]
@0xsimao Losing 10% cost is better than losing total fees.

**Comment by 0xsimao** [comment]
@jsmi0703 yeah I agree but still a loss for the protocol, even more so when they intend to have flexibility when claiming the fees. Feel like repeating a bit these points but it's a summary to justify further why it is important for the protocol to leave unclaimed fees if required:
1. `PointTokenVault::collectFees()` is permissionless, so they may rely on someone else to claim the fees.
2. They don't enforce that fees will be collected before disabling rewards. If we look at the [fix](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/fix-review/point-tokenization-vault/contracts/PointTokenVault.sol#L370), even after reading this issue, they are okay with having pending fees. This makes sense because if the fee is relatively small, they should not be calling it.

As such, there are [situations](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/185#issuecomment-2340400070) where there is no proper way for the admin to procede when we take the design of the protocol into account. They either lose the rewards or lose a significant `%` of rewards to fees.

In [test_FeeCollectionNoRedemptionFee()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/test/PointTokenVault.t.sol#L592) replace
```solidity
vm.expectEmit(true, true, true, true);
emit FeesCollected(eigenPointsId, pointTokenVault.feeCollector(), 0.1e18, 0e18); // No redemption fees
pointTokenVault.collectFees(eigenPointsId);
```
with
```solidity
vm.prank(operator);
uint256 gasLeft = gasleft();
pointTokenVault.setRedemption(eigenPointsId, rewardToken, 0, false);
pointTokenVault.collectFees(eigenPointsId);
console.log(gasLeft - gasleft());
```
and run `forge test --mt test_FeeCollectionNoRedemptionFee -vv --isolate`.

The gas cost shows `128098`. If we [look](https://ycharts.com/indicators/ethereum_average_gas_price) at the gas price this year on the 5th of March, it spiked at `98.68` gwei / gas unit and the ETH price was `3568` USD (google).
These calculations mean that the cost to collect fees would be  `128098  * 98.68 * 1e-9 ETH = 0.01264071064 ETH = 0.01264071064 * 3568 USD = 45` USD.

Taking into account the `0.01%` rule for medium severity, a loss of `45` USD equals an amount of fees of `45 / 0.01 * 100 = 450k` USD. Thus, only if the fees exceeded `450k`, would this be low severity. As the fee may be a value much smaller than that, the issue justifies medium severity.

**Comment by WangSecurity** [comment]
Firstly, big thanks to all the participants of the discussion, really appreciate it, it also brought me some good thoughts.

Secondly, about the issue. If we take the gas spike scenario into consideration, then it also wouldn't be economically viable for the admin to disable redemption fees, because in that case they don't even get any funds, but still spend gas on it.

Moreover, it's not economically viable for anyone besides admins to call `collectFee` for the admins, because again, they don't get any funds or anything and only spend gas on this transaction.

Therefore, if we consider the case that it won't be economically viable for the admin to disable redemptions at gas spikes and it's not economically viable for anyone besides the admin to collect the fees. Therefore, we should very well assume the admin can wait and then both collect the fees and disable redemptions when the gas fees are low.

*Note: I see that the word "viable" might not be the best here, but I hope you understand what I mean. Let me know if you want me to re-iterate*

Moreover, if we consider paying the fees on Eth Mainnet as a loss, then we should also consider the scenarios where the users deposits $50 into the protocol and pays $30 gas fees for that, but I hope we all understand it's not an issue. The gas fee is the cost you pay for using the chain and in that case, we shouldn't consider this as a loss. Otherwise, the issue is in using Mainnet and not other chains.

Therefore, I still stand by me previous decision that this issue should be invalid as the admin can claim all the rewards before disabling redemptions. Planning to accept the escalation.

**Comment by 0xsimao** [comment]
@WangSecurity the problem is that the admin may need to disable redemptions right away and this issue would force him to make 2 additional calls to do so, taking a loss exceeding 0.01%, warranting medium severity. This is not subjective to the definition of 'viable', it matches exactly the definition of the rule.

> Secondly, about the issue. If we take the gas spike scenario into consideration, then it also wouldn't be economically viable for the admin to disable redemption fees, because in that case they don't even get any funds, but still spend gas on it.

It makes no sense to consider economic viability solely when disabling redemptions, it is like saying that pausing a contract may not be economically viable. This is comparing apple to oranges. Disabling redemptions is a time sensitive function because if the admin waits for example 1 more day, people would claim rewards in the meantime, which goes against the intention of the protocol. The fact that the admin intends to disable redemptions does not come into the economic viability question because it is something that would always be done regardless of the bug. What did not need to be done is making the 2 extra function calls and losing 45 USD.

> Moreover, it's not economically viable for anyone besides admins to call collectFee for the admins, because again, they don't get any funds or anything and only spend gas on this transaction.

It makes sense for other users to call `collectFees()` because 1) the fee may be some times bigger than the gas cost and 2) gas costs may lower in the next day, but the admin still needs redemptions to be disabled. Keep in mind that anyone can call collect fees, including users who benefit by harming Rumpel's reputation. For example, an attacker would pay 30 USD in gas fees to make Rumpel lose 30k fees.

> Moreover, if we consider paying the fees on Eth Mainnet as a loss, then we should also consider the scenarios where the users deposits $50 into the protocol and pays $30 gas fees for that, but I hope we all understand it's not an issue. 

No one is forcing users to make deposits and take losses, but the admin here is forced to pay 45 USD to not lose fees. If the admin must spend an extra 45 usd in gas fees to collect 100 fees, this is a 45% loss and qualifies for medium severity.

> The gas fee is the cost you pay for using the chain and in that case, we shouldn't consider this as a loss. Otherwise, the issue is in using Mainnet and not other chains.

No it is not. This gas fee is the cost the admin pays to prevent a 45 USD loss due to the bug. The cost of using the chain is solely disabling the reward token, not making the 2 extra calls to prevent this bug. The admin should never have to pay this 45 USD in the first place.

Either way we look at it, with the current design, there is a loss for the protocol. As such, there are times when there is no proper way to disable redemptions, which means that based on Sherlock's rules, the issue is valid.

**Comment by WangSecurity** [comment]
> It makes no sense to consider economic viability solely when disabling redemptions, it is like saying that pausing a contract may not be economically viable. This is comparing apple to oranges. Disabling redemptions is a time sensitive function because if the admin waits for example 1 more day, people would claim rewards in the meantime, which goes against the intention of the protocol. The fact that the admin intends to disable redemptions does not come into the economic viability question because it is something that would always be done regardless of the bug. What did not need to be done is making the 2 extra function calls and losing 45 USD

Thank you for elaborating on this part. I didn't mean to say it's better for the protocol to wait in this scenario, I meant to say that if we consider the cost of collecting fees, then we can also consider the cost of making other transactions.

> It makes sense for other users to call collectFees() because 1) the fee may be some times bigger than the gas cost and 2) gas costs may lower in the next day, but the admin still needs redemptions to be disabled. Keep in mind that anyone can call collect fees, including users who benefit by harming Rumpel's reputation. For example, an attacker would pay 30 USD in gas fees to make Rumpel lose 30k fees.

About the first two reasons for other users to call `collectFees`, still, there's no economic viability for them to call it, since at any time, even when the fees are lower, there's no profit for them and they spend gas fees on it.

> No it is not. This gas fee is the cost the admin pays to prevent a 45 USD loss due to the bug. The cost of using the chain is solely disabling the reward token, not making the 2 extra calls to prevent this bug. The admin should never have to pay this 45 USD in the first place.

Thank you for elaborating, but, still, we shouldn't consider paying the fees as a loss of funds and collecting the fees before disabling the redemptions leads to no loss of fees. Hence, my decision remains, reject the escalation and leave the issue as it is.

**Comment by 0xHuntoor** [comment]
@WangSecurity you mean accept the escalation?

**Comment by 0xsimao** [comment]
> Thank you for elaborating on this part. I didn't mean to say it's better for the protocol to wait in this scenario, I meant to say that if we consider the cost of collecting fees, then we can also consider the cost of making other transactions.

Why should we consider the cost of making other transactions? The protocol must call disable redemptions and the gas cost of this action alone is the same with or without the bug. There is nothing we can this about the gas cost of calling disabling redemptions alone. However, we can and should fix this bug so the protocol does not take a big loss to claim fees to prevent losing all the fees.
 

> About the first two reasons for other users to call collectFees, still, there's no economic viability for them to call it, since at any time, even when the fees are lower, there's no profit for them and they spend gas fees on it.

Yes there is, if they only pay 30 USD to make Rumpel lose 30k fees, it's very worth to them if they win with Rumpel losing reputation, or do you think otherwise? There is no rule saying these issues should not be considered.

> Thank you for elaborating, but, still, we shouldn't consider paying the fees as a loss of funds and collecting the fees before disabling the redemptions leads to no loss of fees.

Could you explain why? Don't you agree that the protocol pays extra 45 USD to get a fee that may be small such as 100 USD, taking a 45% loss? If yes, how can this be invalidated if it matches the medium severity rule?

It's not subjective if we can consider it a loss or not, it's a fact, the protocol pays an extra 45 USD to claim 100 USD. If the bug didn't exist, no loss. 

The fact that the fee may be very low means this issue can be a very big loss, we have no idea how big it is when redemptions are disabled. As such, a 50% loss or similar is a reality.

**Comment by WangSecurity** [comment]
Thank you for re-iterating, but I still stand on my previous claim that the gas fees shouldn't be considered as a loss of funds. Gas Fees are an operational cost and making an additional transaction is not a loss of funds, while the actual funds (fees in this case) remain intact. 

The decision remains the same, accept the escalation and invalidate this issue (*excuse me for the typo in the previous comment*).

**Comment by 0xsimao** [comment]
@WangSecurity there are 2 key arguments left that are not being taken into account. The first one is defining what a loss is and the second one the fact that the fee may be very small.

Loss is the reduction of funds of the admins. If this loss is due to something intended, well, there is nothing we can do (like your deposit example). However, if it happens due to a bug, this is not the same and puts it in scope. 

Whether we call it an operational cost or not, the fact is there is a loss due to the bug. Not due to the high gas cost, this part just amplifies the severity, but due to the bug. The loss would still exist in other networks, it's just that on Ethereum it becomes bigger. In other words, the loss comes as a direct result of the bug, it's not just a standard operational cost due to higher fees. Simply put, the protocol experiences a reduction of funds because the system is not working as intended.

As such, due to the bug, the funds of the admin objectively reduce by 45 USD. This value is not theoretical, it is empirical, and the calculation was based on scenarios that have happened in the past. Even if we consider a lower gas cost, it is still significant. 

The 3 paragraphs above show that the admin will objectively have the wealth reduced by 45 USD. This matches the definition of loss.

The other very important key point that was overlooked is that the fee may be as small as 100 USD, which is a huge loss % wise, and meets the definition of medium severity. 

What would you consider a loss of funds? What if the attacker made the admin spend 1000 USD gas to collect 100 USD in fees? Wouldn't you consider this a loss? The difference to the current issue is just the magnitude of the numbers, the concept is the same. There is the 0.01% rule that we should follow to judge this issue.

The critical point is that the reduction in funds arises from an unintended bug, making this a vulnerability by definition, as the admin's funds are reduced due to a flaw in the system rather than normal, expected costs.

**Comment by WangSecurity** [comment]
> Loss is the reduction of funds of the admins. If this loss is due to something intended, well, there is nothing we can do (like your deposit example). However, if it happens due to a bug, this is not the same and puts it in scope.

But, in that sense, ever calling `collectFees` is a loss, even if gas fees on mainnet are low, e.g. $3, it would be 3% on 100 USD fees and I disagree that making sure the `collectFees` should be called (not to lose fees) before disabling the redemptions makes it a loss, even if the fees are high.

> Whether we call it an operational cost or not, the fact is there is a loss due to the bug. Not due to the high gas cost, this part just amplifies the severity, but due to the bug. The loss would still exist in other networks, it's just that on Ethereum it becomes bigger.

I understand the high gas fees are just an amplification, but my decision is that making the admin call `collectFees` before disabling redemptions (again, so they don't lose fees) is not a loss of funds (due to paying more gas).

> As such, due to the bug, the funds of the admin objectively reduce by 45 USD. This value is not theoretical, it is empirical, and the calculation was based on scenarios that have happened in the past. Even if we consider a lower gas cost, it is still significant.

To be clear, don't mean to say the value is theoretical, I see it's based on real data, and I don't argue with that. What I'm trying to say, is that the funds, i.e. fees in this case, are not reduced, the admin collects as much fees as they wanted. And again, making the admin collect fees before calling redeeming fees and paying gas for it. 

I'll use an analogy, but don't mind replying to it, if it's not convincing, because discussing it will just unnecessarily extend the escalation. If we consider making someone pay more fees as a loss, then DOSing the transaction for one block should also be a valid issue. Let's take our example, if there was a way to DOS the collect fees transaction for one block, this way, the admin could end up paying 90$ in this case. Therefore, the following rule is pointless:
> Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue.

The similarity here is that in our case the admin suffers a loss by making an additional call before disabling the fees, which as I've said, is not a loss of funds (again to re-iterate, this is only an analogy and if you disagree with it, don't spend time replying to it, we can discuss it in DMs if you want).

> The other very important key point that was overlooked is that the fee may be as small as 100 USD, which is a huge loss % wise, and meets the definition of medium severity.

Yeah, I don't argue that fees can be relatively small, but, I still stand by my decision that paying more gas is not a loss of funds.

> What would you consider a loss of funds? What if the attacker made the admin spend 1000 USD gas to collect 100 USD in fees? Wouldn't you consider this a loss? The difference to the current issue is just the magnitude of the numbers, the concept is the same. There is the 0.01% rule that we should follow to judge this issue.

That's actually a very different scenario (from my perspective) when you can make the other user pay too much gas (by an external call, for example) and it very well might be a valid issue. If you want to discuss such a scenario, we can do that in detail in Discord (either in DMs or in the feedback channel to get more views and opinions), because I don't see it affecting the discussion and escalation.

> The critical point is that the reduction in funds arises from an unintended bug, making this a vulnerability by definition, as the admin's funds are reduced due to a flaw in the system rather than normal, expected costs.

My perspective and the decision is that the funds remain intact (the admin gets as many fees as they wanted to collect) and the fact that the admin has to collect fees before disabling the redemptions (due to completely losing them if they collect after) is not a loss of funds. 

The decision remains, accept the escalation and invalidate the issue.

**Comment by 0xsimao** [comment]
> But, in that sense, ever calling collectFees is a loss, even if gas fees on mainnet are low, e.g. $3, it would be 3% on 100 USD

This is missing the point, here the admin is **forced** to call `collectFees()`, which in this specific codebase goes completely against the [design](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/185#issuecomment-2344305697), which is being overlooked. The whole point of the `collectFees()` function is to be flexible in fee collection (anyone can call it, no hardcoded amount to collect fees). This means that being forced to do the opposite is a vulnerability and is by no means standard, expected behaviour. It is not just a setter or some admin function, but the admin would act in a way that makes no sense given the design of the protocol, taking losses that were not expected and that the code was built in a way to prevent exactly them.

This is why the argument 'ever calling collectFees is a loss', which is the same as the one used [before](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/185#issuecomment-2344871127) (using Ethereum is the vulnerability, and it would mean calling `deposit()` and paying high fees is also a vulnerability) is not applicable. The intention of the design is exactly saying 'I will only collect fees when they stack up to a big amount, until then if someone wants to claim, feel free to do so, but we won't because we'd rather spend less gas and collect when the amount reaches a certain threshold or gas fees are lower'. As such, both depositing and collecting fees when **intended** are expected behaviour and normal operation; being **forced** to collect fees, taking losses that were supposed to be prevented by this specific design, is not.

> I understand the high gas fees are just an amplification

This confirms that the loss is caused by the bug. [1]

As it is caused by the bug, it is a vulnerabilty and we can not say that that whatever funds we have to spend to fix it are not losses. This logic is flawed and that's why I asked the question in the end of my last message
> What if the attacker made the admin spend 1000 USD gas to collect 100 USD in fees?

To which was replied:

> That's actually a very different scenario (from my perspective) when you can make the other user pay too much gas (by an external call, for example) and it very well might be a valid issue.

As such, it is also confirmed that a vulnerability causing the admin to pay extra gas fees is a valid issue. [2]
So the following statements
> I disagree that making sure the collectFees should be called (not to lose fees) before disabling the redemptions makes it a loss

> making the admin call collectFees before disabling redemptions (again, so they don't lose fees) is not a loss of funds (due to paying more gas).

> What I'm trying to say, is that the funds, i.e. fees in this case, are not reduced

> the admin suffers a loss by making an additional call before disabling the fees, which as I've said, is not a loss of funds

> I still stand by my decision that paying more gas is not a loss of funds.

> My perspective and the decision is that the funds remain intact (the admin gets as many fees as they wanted to collect) and the fact that the admin has to collect fees before disabling the redemptions (due to completely losing them if they collect after) is not a loss of funds.

Can not be said because it was just confirmed that making the admin pay too much gas is valid.
The fact that the admin will take the loss and there is no need for attacker intervention (external call) makes this bug even more serious because it's 1 less constraint.

> Yeah, I don't argue that fees can be relatively small

This confirms that the loss can be huge % wise. [3]

So when we join [1], [2] and [3]:
1. The loss is caused by the bug.
2. A bug causing an admin to spend extra gas fees, when the codebase was built specifically to prevent these losses, is a loss.
3. The loss % can be very high - exceeding 0.01%.

The issue is medium severity.

**Comment by 0xHuntoor** [comment]
@WangSecurity again that typo 🥲

You mean to accept the escalation?

**Comment by WangSecurity** [comment]
After @0xsimao and I talked with the sponsor, there are no thresholds of gas price to collect the fees, and they're not considered when calling the `collectFees`. Hence, the design is not to collect fees when it's economically viable. Hence, I stand by my previous statements and decisions. The admin is assumed to collect the fees before disabling the redemptions to not lose any fees. Paying gas fees (even though they can be extremely high on Ethereum) is not a loss of funds. Thus, the fees can be collected without a loss before disabling the redemptions and this issue has to be invalid. Planning to accept the escalation and invalidate the report.

**Comment by 0xsimao** [comment]
> After @0xsimao and I talked with the sponsor, there are no thresholds of gas price to collect the fees, and they're not considered when calling the collectFees.

They said they don't have thresholds but also that they will do it frequently. The frequency is based on the gas costs, otherwise they would claim it every block.

**Comment by Jammabeans** [comment]
@0xsimao 

If I seem relentless, just remember, I learned it from you.

I can see you pointing me to user mistake excuse, but that is not the only issue uncovered in my issue. aside from that impact, the finding also uncovers other impacts.

It shows an attacker stealing the Proof intended for the user, frontrunning them and using that proof with different data. 

That by it's self should qualify as medium, no user mistake is required.

**Comment by WangSecurity** [comment]
They didn't say the frequency is based on the gas costs. Still, my decision remains the same, accept the escalation and invalidate the issue, since the admin can collect the fees before disabling the redemptions to not cause loss of the fees and the paying the gas to collect the fees is not considered a loss of funds.

**Comment by 0xsimao** [comment]
@WangSecurity do you believe they don't take gas costs into account when picking the frequency?

**Comment by WangSecurity** [comment]
Yes, from their responses I believe gas costs are not taken into considerations. Planning to accept the escalation and invalidate the report.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IlIlHunterlIlI](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/185/#issuecomment-2327870457): accepted
