### ISSUE TITLE
dimulski - Users that claim PTokens will pay less fess

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-07-sense-points-marketplace-judging#59]
dimulski

High

# Users that claim PTokens will pay less fess

### Summary

The protocol charges both a minting fee when users claim Ptokens via the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function, and a redemption fee when users redeem their PTokens for the reward tokens via the [redeemRewards()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L172-L226) function. The protocol utilizes a so called "fee on the borders" strategy and as per the readme: *We chose a "fee on the borders" strategy in the vault where users are only charged for redemption if they redeem in excess of what they minted, pToken wise.* What users can redeem without paying the redeem fee is calculated in the following way:
```solidity
    function redeemRewards(Claim calldata _claim, address _receiver) public {
        ...

        uint256 claimed = claimedPTokens[msg.sender][pointsId];
        uint256 feelesslyRedeemed = feelesslyRedeemedPTokens[msg.sender][pointsId];

        // The amount of pTokens that are free to redeem without fee.
        uint256 feelesslyRedeemable = claimed - feelesslyRedeemed;

        uint256 rewardsToTransfer;
        uint256 fee;

        if (feelesslyRedeemable >= pTokensToBurn) {
            // If all of the pTokens are free to redeem without fee.
            rewardsToTransfer = amountToClaim;
            feelesslyRedeemedPTokens[msg.sender][pointsId] += pTokensToBurn;
        } else {
            // If some or all of the pTokens need to be charged a fee.
            uint256 redeemableWithFee = pTokensToBurn - feelesslyRedeemable;
            // fee = amount of pTokens that are not feeless * rewardsPerPToken * redemptionFee
            /// INFO: Equivalent to (x * y) / WAD rounded up
            fee = FixedPointMathLib.mulWadUp(
                FixedPointMathLib.mulWadUp(redeemableWithFee, rewardsPerPToken), redemptionFee
            );

            rewardTokenFeeAcc[pointsId] += fee;
            rewardsToTransfer = amountToClaim - fee;

            if (feelesslyRedeemed != claimed) {
                feelesslyRedeemedPTokens[msg.sender][pointsId] = claimed;
            }
        }
        ...
    }
```
However the **claimedPTokens[msg.sender][pointsId]** mapping is updated before the minting fee is applied in the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function. Thus a user can buy addition pToken via the [convertRewardsToPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L229-L254) function, where he isn't charged a minting fee, and then redeem part of the pTokens without paying a redemption fee as well, which results in the protocol collecting less fees than it should, thus the high severity.  

### Root Cause

The **claimedPTokens[msg.sender][pointsId]** mapping is updated before the minting fee is applied in the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function

### Internal pre-conditions

1. A user claims some amount of pTokens via the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function.
2. The **mintFee** is set to **0.1e18** which is **10%**, and the **redemptionFee** is set to **0.1e18** which is **10%** as well
3. Redemption is set via the [setRedemption()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L313-L319) and users can buy pTokens via the [convertRewardsToPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L229-L254) function.

### Attack Path

1. User A has a **_claim.totalClaimable** = **1e18** for **pTokenA**, and decides to claim all of his pTokens by calling the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function. He gets minted **0.9e18** pTokensA, however the **claimedPTokens** mapping for User A is set to **1e18** in the [_verifyClaimAndUpdateClaimed()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L271-L296) function.
2. Now for easier calculations let's say that the **rewardToken** is **WETH** and the **rewardsPerPToken** is **1e18**, when the user calls the [redeemRewards()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L172-L226) function in order to redeem his **0.9e18** pTokenA he won't pay any redemption fees. So far so good.
3. User A calls the [convertRewardsToPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L229-L254) function, and convert **0.1e18 WET** for pTokensA, he is not charged any minting fee.
4. Now when User A  calls the [redeemRewards()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L172-L226) function again, he won't have to pay redemption fee for the **0.1e18** pTokensA that he has, which results in the protocol not collecting the fees that it is supposed to. *0.1e18 \* 10% = 0.01e18*. If the fees are a bigger percentage the protocol will lose even more, this loss of fees can be accrued an all pTokens that are not merkle based, which results in big losses for the protocol. 

### Impact

Users that have claimed pTokens via the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function, will pay less fees than they are supposed to if they later buy more pTokens via the [convertRewardsToPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L229-L254) function

### Mitigation
Update the **claimedPTokens[msg.sender][pointsId]** mapping, after the minting fee is applied in the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function.

**Comment by AtanasDimulski** [comment]
Escalate,
This issue clearly describes a discrepancy in the way fees are collected, and results in the protocol collecting fewer fees than supposed to. I believe high severity is appropriate.

**Comment by sherlock-admin3** [comment]
> Escalate,
> This issue clearly describes a discrepancy in the way fees are collected, and results in the protocol collecting fewer fees than supposed to. I believe high severity is appropriate. 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by debugging3** [comment]
#19 is dup of this and it is also escalated.

**Comment by 0xsimao** [comment]
This issue is incorrect because it matches the readme, as the user effectively mints `pTokens` equal to the full `claimed` amount. Note that when the fee is collected, the corresponding remaining `pTokens` are [minted](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L347), hence no discrepancy.

**Comment by AtanasDimulski** [comment]
> This issue is incorrect because it matches the readme, as the user effectively mints `pTokens` equal to the full `claimed` amount. Note that when the fee is collected, the corresponding remaining `pTokens` are [minted](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L347), hence no discrepancy.

I don't see how your comment changes the fact that the user can buy more tokens and redeem them without paying a redemption fee.

**Comment by 0xsimao** [comment]
> I don't see how your comment changes the fact that the user can buy more tokens and redeem them without paying a redemption fee.

It's intended, the user mints pTokens (the fee collector does later, but it's due to the user claim) equal to the claimed amount. This means that the user can redeem without fee the full claimed amount.

If the user could only redeem without fees the pTokens minted directly to the user, there would be pTokens in the market (the ones minted by the feeCollector) that would pay a double fee. With the code as is, all pTokens may be redeemed without paying fee twice (claimed == supply of pTokens), which is the intention of the protocol.

**Comment by jsmi0703** [comment]
Let us consider the following scenario:
1. Let mintFee = 10%, redemptionFee = 10%.
2. userA claim 100 pTokens and userB claim 100 pTokens. userA and userB will receive 90 pTokens respectively while they pay 10 pTokens as mintFee respectively. 
3. However claimedPTokens[userA][pointsId] = claimedPTokens[userB][pointsId] = 100 (> 90).
4. Assume that userA sells 10 pTokens to userC who have never claimed any pTokens.
5. userA will redeem 80 pTokens and userB will redeem 90 pTokens feelessly respectively. But userC  should pay 1 pTokens as redemptionFee when he redeem 10 pTokens. It's the result due to the design choice.
6. On the other hand, if userA sells 10 pTokens to userB at step 4, userA will redeem 80 pTokens and userB will redeem 100 pTokens feelessly respectively because claimedPTokens[userB][pointsId] = 100 at step 3. 
7. Step 6 can't be design choice. That is, because userA sells pTokens to userB, userB should pay redemptionFee for bought 10 pTokens, however the implementation is not so.

**Comment by WangSecurity** [comment]
The comment above is a fair argument, but, still, User B redeemed exactly the same amount that was minted, i.e. 100. I see they've got only 90 after the mint, but technically, after their mint 100 ptokens were minted. Hence, in that scenario, they shouldn't pay any excess fees and it's indeed the designed intention of the protocol.

Planning to reject the escalation and leave the issue as it is.

**Comment by AtanasDimulski** [comment]
Hey @WangSecurity I want to clarify that the README specifies what the user minted for himself not what was totally minted by the protocol as it was implied by @0xsimao: *We chose a "fee on the borders" strategy in the vault where users are only charged for redemption if they redeem in excess of what THEY minted*. Clearly the readme is broken, and users are paying less fees than they should, which essentially results in users stealing tokens from the protocol. Thanks for your time!

**Comment by jsmi0703** [comment]
> User B redeemed exactly the same amount that was minted, i.e. 100.

Please don't confuse terms: *claimed vs minted*.

100 is claimed by User B but is not minted to User B. Only 90 is minted to User B. The rest 10 is minted by fee collector (not by User B) to himself after that so fee collector shouldn't pay redemptionFee for 10. However, in the current implementation, fee collector should pay redemptionFee for that 10 (see #19). 

I believe that "fee on the borders" means that if a user redeem what he didn't claim by himself and bought from someone else, he should pay redemptionFee as step 5 of my [comment](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/59#issuecomment-2336703637).

**Comment by jsmi0703** [comment]
@0xsimao  you says:

> It's intended, the user mints pTokens (the fee collector does later, but it's due to the user claim) equal to the claimed amount. This means that the user can redeem without fee the full claimed amount.

It's incorrect. the mintFee is minted by fee collector after that when fee collector wants to collect fees. And user mints only pTokens equal to `claimedAmount - mintFee`.

> If the user could only redeem without fees the pTokens minted directly to the user, there would be pTokens in the market (the ones minted by the feeCollector) that would pay a double fee. With the code as is, all pTokens may be redeemed without paying fee twice (claimed == supply of pTokens), which is the intention of the protocol.

Yes, there would be pTokens in the market that would pay a double fee. But they are minted by fee collector and are owned by fee collectors. Therefore, fee collector (not users) should redeem mintFee without paying fee twice. But the current code doesn't allow fee collector redeem mintFee (what he minted by himself) without paying fee twice (see #19). Rather, it allows users to redeem mintFee without paying fee twice.
Or you mean fee collector must send mintFee to users in order to redeem without paying fee twice? It can be the design choice? I can't believe it.

**Comment by WangSecurity** [comment]
> We chose a "fee on the borders" strategy in the vault where users are only charged for redemption if they redeem in excess of what THEY minted. Clearly the readme is broken, and users are paying less fees than they should, which essentially results in users stealing tokens from the protocol. Thanks for your time

Well, actually, it's the design and how the protocol should function. That's why the entire 100 is assigned to the user, instead of 90 which they received.

> Please don't confuse terms: claimed vs minted.
100 is claimed by User B but is not minted to User B. Only 90 is minted to User B. The rest 10 is minted by fee collector (not by User B) to himself after that so fee collector shouldn't pay redemptionFee for 10. However, in the current implementation, fee collector should pay redemptionFee for that 10 (see https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/19).

Don't worry, I didn't confuse it and used it intentionally. I wanted to say that due this user's deposit, there were 100 tokens minted, even though only 90 were received by the user. Essentially, the user actually mints 100 tokens, but they don't get the 10% of it, because they paid the fee as soon as the tokens were minted. 

So, this is intended and the user indeed should be able to withdraw 100 tokens without fees, even though they've got only 90 out of 100 minted tokens.

**Comment by AtanasDimulski** [comment]
@WangSecurity are you the architect of the protocol. Can you stop insinuating what is a design choice and what is not. The readme clearly states that they minted(they meaning the users), stop trying to spin it like it is claimed. We have the readme from where we can draw actual facts. It is not our job to think what the sponsors may have wanted or not. There is a big difference between claimed and minted.

**Comment by jsmi0703** [comment]
@WangSecurity Thank you for your reply. I'd like to clear some points.

> Don't worry, I didn't confuse it and used it intentionally. I wanted to say that due this user's deposit, there were 100 tokens minted, even though only 90 were received by the user. Essentially, the user actually mints 100 tokens, but they don't get the 10% of it, because they paid the fee as soon as the tokens were minted.

First, only 90 is minted by user and 10 is allowed for fee collector to mint after some time via `pTokenFeeAcc` state variable.  10 is not minted until fee collector calls `collectFees()`. That is, 10 is minted by fee collector (not user) only when fee collector (not user) wants. Clearly, 
`100 is claimed by user, 90 is minted to user by user and 10 is minted to fee collector by fee collector`.

> So, this is intended and the user indeed should be able to withdraw 100 tokens without fees, even though they've got only 90 out of 100 minted tokens.

Second, 90 is owned by user and can be redeemed without redemptionFee but 10 is owned by fee collector and fee collector can't redeem the 10 without fee. Rather, user can redeem more 10 without fee even though he doesn't own the 10. It can't be the design choice. 
Exploiting this vulnerability, user can buy 10 from others and redeem it without redemptionFee. After all, the protocol will lose redemptionFee and fee collector should pay redemptionFee instead of user. The root cause is 
`10 is minted to fee collector but the 10 is allowed for user (not fee collector) to redeem without fee`.

**Comment by WangSecurity** [comment]
@AtanasDimulski I'm not trying to insinuate what the design it, I'm trying to explain to you what the design and how the protocol is expected to work. And here it works exactly as expected. 

Again, I'm not confusing the claimed and minted and I'm trying to explain to you why the protocol works this way. And the user's deposit lead to 100 minted tokens (90 for them and 10 for the fee collector) and the user should be able to redeem 100 feelessly in this scenario. Quoting from the Midas team: "the current design was chosen for impl simplicity and is as intended". The code here works as intended and doesn't violate README as explained above and in the previous comments.


@jsmi0703 :
> First, only 90 is minted by user and 10 is allowed for fee collector to mint after some time via pTokenFeeAcc state variable. 10 is not minted until fee collector calls collectFees(). That is, 10 is minted by fee collector (not user) only when fee collector (not user) wants

I understand that, what I was trying to explain is that it's the user depositing into the protocol initiates the mint of 100 tokens in total, that's why they should be able to redeem these 100 tokens, as said above it's the "implementation simplicity".

> Second, 90 is owned by user and can be redeemed without redemptionFee but 10 is owned by fee collector and fee collector can't redeem the 10 without fee. Rather, user can redeem more 10 without fee even though he doesn't own the 10. It can't be the design choice

But it is, it's the design of the protocol and it works as expected. 

The decision remains, reject the escalation and leave this issue as it is.

**Comment by jsmi0703** [comment]
Although the design is suboptimal, since Midas team confirmed it is as intended, I will accept your opinion and leave this issue. Thank you for your kind explanation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/59/#issuecomment-2329664340): rejected
